# Generated by Django 2.1.7 on 2019-06-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='carrito',
            new_name='carritos',
        ),
    ]
