# Generated by Django 2.1.7 on 2019-06-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_perfil_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('Propietario', 'Propietario'), ('Normal', 'Normal')], default='Normal', max_length=20, null=True),
        ),
    ]
