# Generated by Django 2.1.7 on 2019-06-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20190614_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='carrito/%Y/%m/%d'),
        ),
    ]
