# Generated by Django 2.1.7 on 2019-06-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20190616_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
