# Generated by Django 2.1.7 on 2019-06-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20190616_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='slug',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
