# Generated by Django 2.1.7 on 2019-06-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_auto_20190616_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='producto/%Y/%m/%d'),
        ),
    ]
