# Generated by Django 2.1.7 on 2019-06-17 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_auto_20190616_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='height',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='width',
        ),
    ]
