# Generated by Django 2.1.7 on 2019-06-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_auto_20190616_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, default='No se indica', max_length=50, null=True),
        ),
    ]
